services:
  - type: web
    name: pyannote-diarization
    env: python
    region: frankfurt
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: HF_TOKEN
        sync: false
    healthCheckPath: /health
    healthCheckTimeout: 300
    startupTimeout: 300
    resources:
      - kind: preset
        name: starter
