services:
  - type: web
    name: pyannote-diarization
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "import time; time.sleep(30); import uvicorn; uvicorn.run('main:app', host='0.0.0.0', port=$PORT)"
    healthCheckPath: /health
    envVars:
      - key: HF_TOKEN
        sync: false
    resources:
      - kind: preset
        name: starter
