services:
  - type: web
    name: pyannote-diarization
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: max_split_size_mb:512
    resources:
      - kind: preset
        name: starter
